const STORAGE_KEY='lifeVerseV21';
const now=()=>new Date().toISOString();
const defaultState={activePerson:'rina',people:{
rina:{name:'Rina',avatar:'👩🏻',managed:false,stage:'Adult',roles:['自我管理者','家长','终身学习者'],level:3820,xp:180,nextXp:500,points:200,gameMinutes:0,streak:1,nameSetAt:now(),goals:[{title:'建立稳定的个人成长系统',detail:'把重要目标变成每天真正能执行的小行动',status:'current'}],tasks:[{id:'r1',title:'整理今天最重要的 3 件事',xp:20,points:5,minutes:0,done:false}],ledger:[]},
alex:{name:'Alex',avatar:'🧑‍🚀',managed:true,stage:'Childhood',roles:['学生','科学探索者','运动者'],level:1284,xp:320,nextXp:500,points:145,gameMinutes:30,streak:6,nameSetAt:now(),goals:[{title:'科学探索',detail:'每周完成科学阅读、观察或实验',status:'current'}],tasks:[{id:'a1',title:'数学练习 25 分钟',xp:30,points:8,minutes:10,done:false},{id:'a2',title:'英文阅读 20 分钟',xp:25,points:6,minutes:10,done:false},{id:'a3',title:'科学/历史自由探索',xp:35,points:10,minutes:10,done:false}],ledger:[]},
leo:{name:'Leo',avatar:'🦖',managed:true,stage:'Childhood',roles:['学生','探索者','运动者'],level:932,xp:210,nextXp:400,points:118,gameMinutes:20,streak:4,nameSetAt:now(),goals:[{title:'动物与古生物',detail:'阅读、观察并建立自己的知识卡片',status:'current'}],tasks:[{id:'l1',title:'数学小任务 20 分钟',xp:30,points:8,minutes:10,done:false},{id:'l2',title:'英文阅读 15 分钟',xp:25,points:6,minutes:10,done:false},{id:'l3',title:'动物/恐龙知识任务',xp:35,points:10,minutes:10,done:false}],ledger:[]}},shop:[{id:'s1',title:'额外游戏时间 30 分钟',cost:30,type:'minutes',value:30},{id:'s2',title:'周末零食奖励',cost:50,type:'request'},{id:'s3',title:'选择一次家庭电影',cost:80,type:'request'},{id:'s4',title:'小礼物申请',cost:150,type:'request'}]};
function clone(x){return JSON.parse(JSON.stringify(x))}function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||clone(defaultState)}catch{return clone(defaultState)}}let state=load(),currentView='home';function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}function person(){return state.people[state.activePerson]}
function renderAll(){renderSwitcher();renderHome();renderProfile();renderRoadmap();renderTasks();renderWallet();renderShop();renderFamily()}
function renderSwitcher(){document.getElementById('characterSwitcher').innerHTML=Object.entries(state.people).map(([k,p])=>`<button class="character-button ${k===state.activePerson?'active':''}" onclick="switchPerson('${k}')"><span class="avatar">${p.avatar}</span>${p.name}</button>`).join('')}
function switchPerson(k){state.activePerson=k;save();renderAll();showView(currentView)}
function stats(p){return `<div class="grid grid-3"><div class="stat-card"><div class="stat-icon">◈</div><div><p class="stat-label">HUMAN LEVEL</p><strong class="stat-value">${p.level.toLocaleString()} / 10,000</strong></div></div><div class="stat-card"><div class="stat-icon">◎</div><div><p class="stat-label">钱包积分</p><strong class="stat-value">${p.points}</strong></div></div><div class="stat-card"><div class="stat-icon">🎮</div><div><p class="stat-label">游戏时间</p><strong class="stat-value">${p.gameMinutes} 分钟</strong></div></div></div>`}
function renderHome(){let p=person(),done=p.tasks.filter(t=>t.done).length;document.getElementById('homeView').innerHTML=`<div class="hero-card"><div><p>${p.stage} · ${p.roles.join(' · ')}</p><h3>${p.name}</h3><p>今天先完成真正重要的事。你有 ${p.tasks.length-done} 项行动待完成。</p><div class="progress-wrap"><div class="progress-bar"><div class="progress-fill" style="width:${Math.min(100,p.level/100)}%"></div></div><div class="progress-meta"><span>Human Lv. ${p.level.toLocaleString()}</span><span>Lifetime · 10,000</span></div></div></div><div class="hero-emoji">${p.avatar}</div></div>${stats(p)}<div class="grid grid-2 section-spacer"><div class="panel"><h3>🎯 当前目标</h3><strong>${p.goals[0]?.title||'还没有目标'}</strong><p class="muted">${p.goals[0]?.detail||'去目标页添加你的第一个目标。'}</p><button class="btn-secondary" onclick="showView('roadmap')">查看目标</button></div><div class="panel"><h3>✓ 今日进度</h3><p class="muted">${done}/${p.tasks.length} 已完成 · 连续 ${p.streak} 天</p><button class="btn-primary" onclick="showView('tasks')">开始行动</button></div></div>`}
function renderProfile(){let p=person(),set=new Date(p.nameSetAt),next=new Date(set);next.setFullYear(next.getFullYear()+1);let can=Date.now()>=next.getTime();document.getElementById('profileView').innerHTML=`<div class="grid grid-2"><div class="panel"><h3>${p.avatar} Life Profile</h3><div class="field"><label>LifeVerse Name</label><input id="profileName" value="${p.name}" ${can?'':'disabled'}></div><p class="muted">${can?'现在可以修改。修改后将再次锁定 365 天。':`名字已锁定。下次可修改：${next.toLocaleDateString('zh-CN')}`}</p>${can?'<button class="btn-primary" onclick="changeName()">保存并锁定名字</button>':''}</div><div class="panel"><h3>人生角色</h3><p>${p.roles.map(r=>`<span class="pill">${r}</span>`).join(' ')}</p><p class="muted">当前人生阶段：${p.stage}</p><p class="muted">角色系统先保持简单，后续再发展 Skill Tree。</p></div></div>`}
function changeName(){let p=person(),v=document.getElementById('profileName').value.trim();if(!v)return;if(!confirm(`确定使用“${v}”吗？保存后 365 天不能再次修改。`))return;p.name=v;p.nameSetAt=now();save();renderAll()}
function renderRoadmap(){let p=person();document.getElementById('roadmapView').innerHTML=`<div class="panel"><h3>${p.name} · 目标</h3>${p.goals.map(g=>`<div class="road-card"><strong>${g.title}</strong><span class="muted">${g.detail}</span></div>`).join('')}<div class="form-grid section-spacer"><div class="field"><label>目标名称</label><input id="goalTitle"></div><div class="field"><label>目标说明</label><input id="goalDetail"></div></div><button class="btn-primary section-spacer" onclick="addGoal()">添加目标</button></div>`}function addGoal(){let t=document.getElementById('goalTitle').value.trim(),d=document.getElementById('goalDetail').value.trim();if(!t)return;person().goals.push({title:t,detail:d,status:'current'});save();renderAll()}
function renderTasks(){let p=person();document.getElementById('tasksView').innerHTML=`<div class="panel"><h3>${p.name} · 今日任务</h3><div class="task-list">${p.tasks.map(t=>`<div class="task-item ${t.done?'done':''}"><div class="task-main"><button class="task-check" onclick="toggleTask('${t.id}')">${t.done?'✓':''}</button><div><div class="task-title">${t.title}</div><div class="muted">+${t.xp} XP · +${t.points} ◎ ${t.minutes?`· +${t.minutes}分钟 🎮`:''}</div></div></div></div>`).join('')}</div></div>`}
function toggleTask(id){let p=person(),t=p.tasks.find(x=>x.id===id);if(!t)return;if(!t.done){t.done=true;p.xp+=t.xp;p.points+=t.points;p.gameMinutes+=t.minutes||0;p.ledger.unshift({time:now(),text:`完成：${t.title}`,amount:t.points});if(p.xp>=p.nextXp&&p.level<10000){p.xp-=p.nextXp;p.level++}}else{t.done=false;p.xp=Math.max(0,p.xp-t.xp);p.points=Math.max(0,p.points-t.points);p.gameMinutes=Math.max(0,p.gameMinutes-(t.minutes||0));p.ledger.unshift({time:now(),text:`撤销：${t.title}`,amount:-t.points})}save();renderAll()}
function renderWallet(){let p=person();document.getElementById('walletView').innerHTML=`${stats(p)}<div class="panel section-spacer"><h3>钱包记录</h3>${p.ledger.length?p.ledger.slice(0,20).map(x=>`<div class="ledger"><span>${new Date(x.time).toLocaleString('zh-CN')} · ${x.text}</span><strong>${x.amount>0?'+':''}${x.amount} ◎</strong></div>`).join(''):'<p class="muted">还没有记录。完成任务后会自动记账。</p>'}</div>`}
function renderShop(){let p=person();document.getElementById('shopView').innerHTML=`<div class="panel"><h3>◇ Reward Shop</h3><p class="muted">当前余额 ${p.points} ◎。XP 不可消费，积分和游戏时间分别记录。</p><div class="shop-grid">${state.shop.map(i=>`<div class="shop-card"><h3>${i.title}</h3><strong>${i.cost} ◎</strong><button class="btn-primary" onclick="buy('${i.id}')" ${p.points<i.cost?'disabled':''}>兑换</button></div>`).join('')}</div></div>`}function buy(id){let p=person(),i=state.shop.find(x=>x.id===id);if(!i||p.points<i.cost)return;if(!confirm(`使用 ${i.cost} 积分兑换“${i.title}”？`))return;p.points-=i.cost;if(i.type==='minutes')p.gameMinutes+=i.value;p.ledger.unshift({time:now(),text:`兑换：${i.title}`,amount:-i.cost});save();renderAll();alert(i.type==='request'?'兑换申请已记录，请由家庭管理者线下兑现。':'兑换成功！')}
function renderFamily(){let p=person();if(!p.managed){document.getElementById('familyView').innerHTML=`<div class="panel"><h3>Family · 家庭管理</h3><p>你现在查看的是自己的账号。你可以自我管理，不需要“家长后台”。</p><p class="muted">切换到 Alex 或 Leo，可以添加他们的任务和奖励。</p></div>`;return}document.getElementById('familyView').innerHTML=`<div class="grid grid-2"><div class="panel"><h3>给 ${p.name} 新增任务</h3><div class="field"><label>任务</label><input id="newTaskTitle" placeholder="例如：阅读 20 分钟"></div><div class="form-grid section-spacer"><div class="field"><label>XP</label><input id="newXp" type="number" value="25"></div><div class="field"><label>积分</label><input id="newPoints" type="number" value="5"></div><div class="field"><label>游戏分钟</label><input id="newMinutes" type="number" value="0"></div></div><button class="btn-primary section-spacer" onclick="addTask()">添加任务</button></div><div class="panel"><h3>手动奖励</h3><p class="muted">用于阅读、运动、帮助家人等额外行动。</p><button class="btn-secondary" onclick="bonus(5)">+5 ◎</button> <button class="btn-secondary" onclick="bonus(15)">+15 ◎</button></div></div>`}function addTask(){let p=person(),title=document.getElementById('newTaskTitle').value.trim();if(!title)return;p.tasks.push({id:`t${Date.now()}`,title,xp:+document.getElementById('newXp').value||0,points:+document.getElementById('newPoints').value||0,minutes:+document.getElementById('newMinutes').value||0,done:false});save();renderAll();alert('任务已添加')}function bonus(n){let p=person();p.points+=n;p.ledger.unshift({time:now(),text:'家庭手动奖励',amount:n});save();renderAll()}
function showView(v){currentView=v;document.querySelectorAll('.view').forEach(e=>e.classList.remove('active'));document.getElementById(v+'View').classList.add('active');document.querySelectorAll('.nav-item').forEach(e=>e.classList.toggle('active',e.dataset.view===v));document.getElementById('pageTitle').textContent={home:'今天，继续你的人生。',profile:'Life Profile · 角色',roadmap:'把目标变成行动',tasks:'今天的现实行动',wallet:'Wallet · 钱包',shop:'Reward Shop · 商店',family:'Family · 家庭管理'}[v]}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));renderAll();