// LifeVerse V2.4 — Duolingo-inspired life paths + editable reward shop/assets
function ensureV24(){if(!state.assetTypes)state.assetTypes=[{id:'points',name:'成长积分',icon:'◎',active:true},{id:'game',name:'游戏时间',icon:'🎮',active:true}];Object.values(state.people).forEach(p=>{p.goals=(p.goals||[]).map(g=>({...g,id:g.id||'g'+Math.random().toString(36).slice(2),children:g.children||[]}));});save()}ensureV24();
function renderRoadmap(){let p=person();document.getElementById('roadmapView').innerHTML=`<div class="path-shell"><div class="path-title"><span>✦ LIFE PATH · 人生路线</span><h3>大目标，拆成一关一关。</h3><p>总目标 → 子目标 → 真实任务。完成现实行动，解锁下一段人生。</p></div>${p.goals.length?p.goals.map((g,gi)=>`<section class="big-goal"><div class="goal-banner"><div><small>MAIN GOAL ${gi+1}</small><h3>${g.title}</h3><p>${g.detail||'持续成长中'}</p></div><b>${g.children.filter(c=>c.done).length}/${g.children.length}</b></div><div class="duo-path">${g.children.map((c,i)=>`<div class="path-node ${c.done?'cleared':''} ${i===0||g.children[i-1]?.done?'unlocked':'locked'}" style="--shift:${[0,55,85,45,-20,-70,-45][i%7]}px"><button onclick="toggleSubGoal('${g.id}','${c.id}')">${c.done?'✓':i+1}</button><div><strong>${c.title}</strong><small>${c.done?'CLEARED · 已完成':i===0||g.children[i-1]?.done?'NEXT QUEST · 下一关':'LOCKED · 未解锁'}</small></div></div>`).join('')||'<div class="empty-quest">还没有子目标。先添加第一关。</div>'}</div><div class="add-sub"><input id="sub-${g.id}" placeholder="新增子目标 / New milestone"><button class="glow-button" onclick="addSubGoal('${g.id}')">＋ 添加一关</button></div></section>`).join(''):'<div class="panel empty-path"><h3>🌌 你的路线还没有开始</h3><p>建立第一个总目标，再把它拆成可以闯关的小目标。</p></div>'}<div class="panel new-main-goal"><h3>＋ 新建总目标 / Main Goal</h3><div class="form-grid"><div class="field"><label>总目标</label><input id="goalTitle" placeholder="例如：提升英语能力"></div><div class="field"><label>说明</label><input id="goalDetail" placeholder="为什么这件事重要？"></div></div><button class="btn-primary section-spacer" onclick="addGoal()">创建人生路线</button></div></div>`}
function addGoal(){let p=person(),t=document.getElementById('goalTitle').value.trim(),d=document.getElementById('goalDetail').value.trim();if(!t)return;p.goals.push({id:'g'+Date.now(),title:t,detail:d,children:[]});log(p,'GOAL',`新增总目标：${t}`,p.name);save();renderAll();showView('roadmap')}
function addSubGoal(gid){let p=person(),g=p.goals.find(x=>x.id===gid),el=document.getElementById('sub-'+gid),t=el?.value.trim();if(!g||!t)return;g.children.push({id:'sg'+Date.now(),title:t,done:false});log(p,'GOAL',`“${g.title}”新增子目标：${t}`,p.name);save();renderAll();showView('roadmap')}
function toggleSubGoal(gid,sid){let p=person(),g=p.goals.find(x=>x.id===gid),i=g?.children.findIndex(x=>x.id===sid);if(i<0)return;if(i>0&&!g.children[i-1].done&&!g.children[i].done)return alert('先完成上一关，才能解锁这里。');let c=g.children[i];c.done=!c.done;log(p,'GOAL',`${c.done?'完成':'撤销'}子目标：${g.title} → ${c.title}`,p.name);save();renderAll();showView('roadmap')}
function renderShop(){let p=person();document.getElementById('shopView').innerHTML=`<div class="feature-head"><span>◇ REWARD SHOP · 奖励商店</span><h3>把现实中的努力，换成值得期待的奖励。</h3></div><div class="shop-grid">${state.shop.filter(i=>i.active!==false).map(i=>`<div class="shop-card neon-card"><span class="shop-gem">✦</span><h3>${i.title}</h3><strong>${i.cost} ◎</strong><button class="btn-primary" onclick="buy('${i.id}')" ${p.points<i.cost?'disabled':''}>兑换 REDEEM</button></div>`).join('')||'<p class="muted">还没有启用的奖励。</p>'}</div>${!p.managed?shopAdmin():''}`}
function shopAdmin(){return `<div class="panel section-spacer"><h3>⚙ Shop Manager · 商店管理</h3><p class="muted">可以新增、修改、停用项目；已有兑换历史不会删除。</p>${state.shop.map(i=>`<div class="manage-row"><span><b>${i.title}</b><small>${i.cost} ◎ · ${i.active===false?'已停用':'使用中'}</small></span><button class="btn-secondary" onclick="editShop('${i.id}')">修改</button><button class="btn-secondary" onclick="toggleShop('${i.id}')">${i.active===false?'恢复':'停用'}</button></div>`).join('')}<button class="btn-primary section-spacer" onclick="addShopItem()">＋ 新增奖励项目</button></div>`}
function addShopItem(){let title=prompt('奖励名称 / Reward name');if(!title)return;let cost=+prompt('需要多少积分？','50');if(!Number.isFinite(cost)||cost<0)return;state.shop.push({id:'s'+Date.now(),title,cost,type:'request',active:true});save();renderAll();showView('shop')}
function editShop(id){let i=state.shop.find(x=>x.id===id);if(!i)return;let title=prompt('奖励名称',i.title);if(!title)return;let cost=+prompt('积分价格',i.cost);if(!Number.isFinite(cost)||cost<0)return;i.title=title;i.cost=cost;save();renderAll();showView('shop')}
function toggleShop(id){let i=state.shop.find(x=>x.id===id);if(!i)return;i.active=i.active===false;save();renderAll();showView('shop')}
function renderWallet(){let p=person();document.getElementById('walletView').innerHTML=`<div class="feature-head"><span>◎ GROWTH ASSETS · 成长资产</span><h3>你积累的，不只是分数。</h3></div><div class="asset-vault">${state.assetTypes.filter(a=>a.active).map(a=>`<div class="asset-orb"><em>${a.icon}</em><b>${a.id==='points'?p.points:a.id==='game'?p.gameMinutes:0}</b><span>${a.name}</span></div>`).join('')}</div>${!p.managed?assetAdmin():''}<div class="panel section-spacer"><h3>Activity Ledger · 永久记录</h3><p class="muted">余额可以变化，历史不能删除。</p>${p.history.map(x=>`<div class="ledger"><span>${new Date(x.time).toLocaleString('zh-CN')} · [${x.type}] ${x.text}<small> · ${x.actor}</small></span></div>`).join('')}</div>`}
function assetAdmin(){return `<div class="panel section-spacer"><h3>⚙ Asset Manager · 成长资产管理</h3>${state.assetTypes.map(a=>`<div class="manage-row"><span><b>${a.icon} ${a.name}</b><small>${a.active?'使用中':'已停用'}</small></span>${!['points','game'].includes(a.id)?`<button class="btn-secondary" onclick="toggleAsset('${a.id}')">${a.active?'停用':'恢复'}</button>`:'<small>核心资产</small>'}</div>`).join('')}<button class="btn-primary section-spacer" onclick="addAsset()">＋ 新增资产类别</button></div>`}
function addAsset(){let name=prompt('资产名称，例如：阅读币');if(!name)return;let icon=prompt('图标（可输入一个 Emoji）','✦')||'✦';state.assetTypes.push({id:'a'+Date.now(),name,icon,active:true});save();renderAll();showView('wallet')}
function toggleAsset(id){let a=state.assetTypes.find(x=>x.id===id);if(!a)return;a.active=!a.active;save();renderAll();showView('wallet')}
const v24OldHome=renderHome;renderHome=function(){v24OldHome();let p=person(),stage=document.querySelector('.player-stage');if(stage){stage.classList.add('character-pose-home');stage.insertAdjacentHTML('beforeend','<span class="pose-note">AVATAR · HOME POSE</span>')}};
renderAll();showView('home');