// LifeVerse V2.7 — concept-art matched functional dashboard
(function(){
const art={rina:{face:'✦',role:'创造者 · 规划者 · 探索者',en:'Create · Explore · Inspire'},roy:{face:'▲',role:'支持者 · 探索者 · 家长',en:'Support · Adventure · Together'},alex:{face:'◆',role:'科学 · 历史 · 赛艇',en:'Science · History · Rowing'},leo:{face:'●',role:'动物 · 游戏 · 探索',en:'Animals · Games · Explore'}};
function k(){return state.activePerson||'rina'} function A(){return art[k()]||art.rina}
function visible(){return Object.entries(state.people).filter(([id,p])=>p.active&&(!window.lifeVerseViewer||window.lifeVerseViewer==='rina'||id===window.lifeVerseViewer||(window.lifeVerseViewer==='roy'&&['roy','alex','leo'].includes(id))))}
function tasks(p){return p.tasks.length?p.tasks.slice(0,4).map((t,i)=>`<div class="lv27-task ${t.done?'done':''}"><button onclick="toggleTask('${t.id}')">${t.done?'✓':'□'}</button><i>${['▣','✦','▲','◇'][i%4]}</i><span>${t.title}</span><b>+${t.xp||0} XP</b></div>`).join(''):`<div class="lv27-empty">今天还没有任务 · No quests yet</div>`}
function member(id,p){let x=art[id]||art.rina;return `<button class="lv27-person ${id===k()?'active':''}" onclick="switchPerson('${id}')"><i>${x.face}</i><span><b>${p.name}</b><small>${id==='rina'?'Owner':id==='roy'?'Dad':id==='alex'?'哥哥':'弟弟'}</small></span></button>`}
renderHome=function(){let p=person(),x=A(),done=p.tasks.filter(t=>t.done).length,total=p.tasks.length,goal=p.goals[0];document.getElementById('homeView').innerHTML=`<div class="lv27-shell">
<section class="lv27-topline"><div class="lv27-greet">☀ <b>Good evening, ${p.name}!</b><small>晚上好！今天也在创造更好的自己！</small></div><div class="lv27-people">${visible().map(([id,v])=>member(id,v)).join('')}<button class="lv27-plus">＋</button></div><blockquote>“Small steps every day<br>make a big life.”</blockquote></section>
<section class="lv27-world"><div class="lv27-world-copy"><em>Different Paths,<br>One Family,<br>A Brighter Tomorrow.</em><small>不同的道路，同一个家。<br>更广阔的世界。</small></div><div class="lv27-moon"></div><div class="lv27-crystals"><i></i><i></i><i></i><i></i><i></i></div><div class="lv27-island i1"></div><div class="lv27-island i2"></div><div class="lv27-island i3"></div><div class="lv27-family-art"><div class="char rina"><i>✦</i><b>Rina</b><small>Create<br>Explore<br>Inspire</small></div><div class="bot">●<span>◡</span></div><div class="char roy"><i>▲</i><b>Roy</b><small>Support<br>Adventure<br>Together</small></div><div class="char alex"><i>◆</i><b>Alex</b><small>Science<br>History<br>Rowing</small></div><div class="char leo"><i>●</i><b>Leo</b><small>Games<br>Animals<br>Explore</small></div></div></section>
<aside class="lv27-profile"><div class="lv27-profile-head"><i>${x.face}</i><span><h3>${p.name}</h3><small>${x.role}</small></span><button onclick="showView('settings')">编辑资料</button></div><p>“Small steps every day make a big life.”</p><div class="lv27-level"><b>Human Lv. ${p.level}</b><span>${p.xp} / ${p.nextXp} XP</span><u><i style="width:${Math.min(100,p.xp/p.nextXp*100)}%"></i></u></div><div class="lv27-statgrid"><button onclick="showView('wallet')">◎<b>${p.points}</b><small>积分<br>Points</small></button><button onclick="showView('wallet')">🎮<b>${p.gameMinutes}</b><small>游戏时间<br>Game Time</small></button><button onclick="showView('achievements')">★<b>0</b><small>成就<br>Badges</small></button><button onclick="showView('family')">△<b>${visible().length}</b><small>家庭成员<br>Family</small></button></div></aside>
<section class="lv27-tasks"><header><h3>▣ 今日任务 <small>Today's Tasks (${done}/${total})</small></h3><button onclick="showView('tasks')">查看全部 ›</button></header>${tasks(p)}<button class="lv27-start" onclick="showView('tasks')">▶ <b>开始任务</b><small>Start Quest</small></button></section>
<section class="lv27-week"><header><h3>✦ 本周进度 <small>Weekly Progress</small></h3><b>${total?Math.round(done/total*100):0}%</b></header><div class="lv27-days">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((d,i)=>`<span><i class="${i<done?'on':''}"></i><small>${d}</small></span>`).join('')}</div><div class="lv27-chest">🎁<small>完成 7 天<br>解锁宝箱!</small></div></section>
<section class="lv27-bottom"><button class="goal" onclick="showView('roadmap')"><h3>◉ 我的目标 <small>My Goals</small></h3><div class="mini-scene">⛰ ✦ ⛰</div><p>${goal?.title||'建立更好的自己 · A Better Me'}</p><b>查看目标 · View Goals</b></button><button class="assets" onclick="showView('wallet')"><h3>◇ 成长资产 <small>Growth Assets</small></h3><div class="asset-grid"><i>★<b>${p.points}</b><small>积分</small></i><i>🎮<b>${p.gameMinutes}</b><small>游戏时间</small></i><i>▣<b>0</b><small>阅读币</small></i><i>⌁<b>0</b><small>运动徽章</small></i></div></button><button class="shop" onclick="showView('shop')"><h3>◇ 奖励商店 <small>Reward Shop</small></h3><div class="shop-scene">GOOD IDEAS<br><strong>● ◡ ●</strong></div><b>进入商店 · Visit Shop</b></button><button class="family" onclick="showView('family')"><h3>♧ 家庭 <small>Family</small></h3><div class="family-scene">♙ ♟ ♙ ♟</div><p>Different Paths, One Family.</p><b>进入家庭 · Family Center</b></button></section>
</div>`};
renderAll();showView('home');
})();